version: 2
updates:
  - package-ecosystem: pip
    directories:
      - /impalaai
      - /monitoring/lambdatos3
      - /runner
    ignore:
      - dependency-name: impalaai
    schedule:
      interval: daily
